# See https://github.com/actions/labeler

'actions':
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**

'area: projects':
  - changed-files:
      - any-glob-to-any-file:
          - README.md

'area: scripts':
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**

